### ISSUE TITLE
applicability of generated models

### ISSUE THREAD

**Issue by BanafshehAzizi** [epsilonlabs/haetae#1]
I can't understand where are the applicability of ETL model, variable resolved ETL model and type resolved ETL model.
For transform (declarative part of) ETL transformation to special DSL transformation, we should firstly transform ETL transformation to its model equivalent. Haetae can generate 3 models from ETL transformation. If I use only ETL model (and don't use variable and type reolved etl models), can I do HOT? if not, why not?

**Comment by wrwei** [comment]
Hi there,

ETL variable/type resolved models are used in conjunction with the static analyser, so that we could perform advanced analytics on the programs. For HOT you only need ETL model. As a matter of fact, type related information cannot be persisted to files (they are transient) either. So for HOT you only need to worry about ETL models.

Hope this helps.

Cheers,
Will

**Comment by BanafshehAzizi** [comment]
Many thanks for your kind help
